# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Ensure all non-API requests go to index.html (for SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
